### ISSUE TITLE
[setting] SoccerBeat 초기 세팅

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#1]
## 🐲 Description
SoccerBeat 초기 세팅

## 🧑‍💻 Todo
- [x] 프로덕트 네이밍 확정
- [x] Xcode 프로젝트 생성
- [x] gitignore .DS_Store 추가
- [x] 애플워치 익스텐션 추가
- [ ] SwiftLint 적용 및 세팅

## ✏️ ETC
1번 이슈는 제가 가져갑니다~~
