### ISSUE TITLE
[feat] Watch에서 Route 정보 저장하기 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#114]
## 🐲 Description
- WatchOS 에서 Route 정보를 저장하는지 검사하고 테스트합니다.  [Creating a workout route_AppleDoc](https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/creating_a_workout_route)

## 🧑‍💻 Todo
- [x] 공식문서 따라서 가보기
- [x] WorkoutManager 리펙토링
- [x] CLLocation을 iPhone에서 Read
- [x] CLLocation을 WatchOS에서 저장

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
