### ISSUE TITLE
[fix] iOS HealthKit 예외처리

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#125]
## 🐲 Description
iOS HealthKit 예외처리를 합니다.

## 🧑‍💻 Todo
- [x] HealthKit 건강 데이터 요청 개선.
- [ ] 허용하지 않았다면 보여질 화면 구현.
- [ ] 허용하지 않았다면 다시 허용 요청.

## ✏️ ETC
The authorization status for an HKObjectType does not reflect whether your application has authorization to read samples of those types. It only indicates whether you have requested authorization at all and whether your app is authorized to write samples of those types. So if your app requests authorization to read step count samples but not write them, and the user grants read authorization, then the authorization status for HKQuantityTypeIdentifierStepCount will be HKAuthorizationStatusSharingDenied.

The following is from the [HealthKit framework reference](https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKHealthStore_Class/index.html#//apple_ref/occ/instm/HKHealthStore/authorizationStatusForType:) and explains why your app may not query whether it has read access

_To help prevent possible leaks of sensitive health information, your app cannot determine whether or not a user has granted permission to read data. If you are not given permission, it simply appears as if there is no data of the requested type in the HealthKit store. If your app is given share permission but not read permission, you see only the data that your app has written to the store. Data from other sources remains hidden._

`if self.healthStore.authorizationStatus(for: HKObjectType.workoutType()) == .sharingDenied`

- https://velog.io/@yoogail/iOS-HealthKit-read%EC%97%90-%EB%8C%80%ED%95%9C-%EC%A0%91%EA%B7%BC-%EA%B6%8C%ED%95%9C-%ED%99%95%EC%9D%B8feat.-%ED%99%95%EC%9D%B8-%EB%B6%88%EA%B0%80
- https://stackoverflow.com/questions/29076655/healthkit-authorisation-status-is-always-1/29128231#29128231
