### ISSUE TITLE
[feat] 프로필 사진 편집 디테일 수정

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#134]
## 🐲 Description
프로필 사진 선택 디테일

## 🧑‍💻 Todo
- [x] 프로필 사진 수정 버튼 넣습니다
- [x] 프로필 사진 방패 모양 크롭 (path) 만듭니다
- [x] 프로필 사진 선택 후 카드 전면 먼저 등장

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
