### ISSUE TITLE
[feat] 워치 메인 화면 디자인 리뷰 반영

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#135]
## 🐲 Description
작업 내용을 작성해 주세요.
- 워치 메인 화면 작업에서 오늘 디자인 리뷰를 반영하려 합니다. 

<img width="248" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/1de5a59d-3f67-41b4-8d2b-123ca66bee7d">

## 🧑‍💻 Todo
- [x] 글자 위치 변경
- [x] 경기 시간에 틴트색 적용
- [x] 100분 넘어갔을 때 표현 방식 수정, ex) "120:4"
- [x] 심장 박동 애니메이션 제거 
- [x] 윤곽선 추가 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
