### ISSUE TITLE
[feat] 그래프 데이터 Min, Max 구현 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#136]
## 🐲 Description
작업 내용을 작성해 주세요.
최근 9 경기에 대해서 여러 지표를 그래프로 표현하고 그 안에서 최소값과 최대값을 포현해보겠습니다. 

## 🧑‍💻 Todo
- [ ] HealthKit에서 데이터를 읽어오기, 현행 Workout Route 정보에서 Metadata로 전달 
- [x] 뛴 거리에서 그래프 표현
- [x] 스프린트 횟수 그래프 표현
- [x] 최고 속도 그래프 표현
- [x] 심박수 그래프 표현 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
- 메인 뷰의 경기 분석 뷰에서도 쓸 수 있도록 적용 - 최근 4경기 
<img width="345" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/1a90603e-2899-46cc-bc73-bc7e767189ac">

- 뛴 거리 
<img width="171" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/c5418741-fef8-43f6-bb4b-8dee3beacedb">

- 스프린트
<img width="179" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/767c045f-41ae-4a55-b2d0-48f9a75b3143">

- 스피드 
<img width="199" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/c90f1312-8576-4b40-89d6-a7fde33f452b">

- 분석 상세
<img width="211" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/bf0686e5-d80a-48fa-9d75-b6682f27bbf4">
