### ISSUE TITLE
[feat] ProgressView 작업

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#14]
## 🐲 Description
현재 어느 심장박동 존에 위치하고 있는지 알려주고 경과 시간, 뛴 거리 등을 알려주는 뷰를 작업하려고 합니다. 

## 🧑‍💻 Todo
- [ ] Apple Watch View 그리기 작업
    - [ ] 글자 outline 처리
    - [x] 숫자 + bpm 그라데이션 연속성 주기 
    - [x] "뛴 거리", "경기 시간" 색상넣기
    - [x] 프로그레스바 분절해서 넣기
    - [x] Zone 별로 강조 컬러 나누기 
    - [x] “80 bpm” 그라데이션 넣기
    - [x] Zone, 색상 그라데이션 넣기
    - [x] Color Extension 추가 

## ✏️ ETC
피곤하실 텐데 김밥 한 줄 드시면서 하세요 ~ `@))))))`
