### ISSUE TITLE
[feat] 측정 시작시 아이폰 모달

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#15]
## 🐲 Description
측정 시작시 아이폰 모달뷰 호출.

## 🧑‍💻 Todo
- [ ] 측정 시작 모달뷰 구현
- [ ] 애플워치 측정 시작 인식
- [ ] 아이폰에서 모달뷰 호출

## ✏️ ETC
