### ISSUE TITLE
[feat] spider chart 디자인 개선

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#160]
## 🐲 Description
spider chart 디자인 개선.

## 🧑‍💻 Todo
- [x] spider chart 모서리 곡률 변경.
- [x] 그래프 두개 그릴수 있도록 개선.
- [x] 선으로만 된 그래프 추가.

## ✏️ ETC
