### ISSUE TITLE
[feat] watchOS sprint 및 디테일 수정

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#165]
## 🐲 Description
- 워치 스프린트 모달 화면
- 기타 디테일 수정

## 🧑‍💻 Todo
- [x] 스프린트 모달
- [x] 스프린트 게이지바 배경
- [x] 스프린트 게이지바 색상 변경
- [x] 초 단위 그냥 보여주기
- [x] 3 2 1 화면 중앙에 잘 배치하기 
- [x] 로티 배경 넣기
