### ISSUE TITLE
[feat] 생성된 디자인 시스템에 따라서 Spacing, Font, Color 조정 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#173]
## 🐲 Description

<img width="865" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/e1a5f2ba-7df5-4558-89b7-061d0fd5ac55">

<img width="292" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/937d7578-dc39-4ff5-8d46-a5511e015b18">

Spacing, Font, Color, LinaerGradient 에 맞춰서 작업을 해볼게요.
Spacing  객체는 추가될 것 같고요, Font, Color, LinearGradient 는 수정이 필요하겠습니다. 

## 🧑‍💻 Todo
- [ ] Spacing Contrast 추가
- [ ] Font 사용하는 것만 남기고 삭제
- [ ] Color 사용하는 것만 남기고 삭제
- [ ] LinearGradient 사용하는 것만 남기고 삭제 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
다수의 충돌이 예상됩니다.
