### ISSUE TITLE
[fix] Chart에서 폰트 수정

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#202]
## 🐲 Description
작업 내용을 작성해 주세요.
<img width="339" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/308c98ea-b526-4584-8c87-9d0037019c04">

- Chart에서 "날일" 단위 폰트, 컬러 적용
- "회" 폰트 적용
- 아래에 설명 폰트, 컬러 적용 
- - 글도 맞춰 적용
<img width="439" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/ef862be6-ecb9-491d-9c3c-b5a7db7396d4">

## 🧑‍💻 Todo
- [ ] 글도 맞춰 적용
- [ ] 아래에 설명 폰트, 컬러 적용
- [ ] 차트뷰에서 날,일 + 단위 폰트 컬러 적용

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
