### ISSUE TITLE
[feat] 워치 권한 받지 않을 때 안내 화면

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#206]
## 🐲 Description
위치 정보를 꼭 받아와야 하기 때문에 관련 안내문을 작성하고 시작버튼을 가렸습니다. 

## 🧑‍💻 Todo
- [x] 헬스킷 권한이 없을 때 
- [x] 워치 권한이 없을 때
- [x] 위치 권한 받는 것을 앱 시작 화면에서 실행하기-

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
싱크를 받는 타이밍이 고민이 됩니다. 그래서 지금은 앱 실행 시에 무조건 한 번 껏다 켜도록 하고 있는데요 - 흐름에 불편함이 있다고 생각합니다.
