### ISSUE TITLE
[feat] AnalyticsView 차트 커스터마이징

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#21]
## 🐲 Description
차트 세부 사항 수정합니다. 

## 🧑‍💻 Todo
- [x] 바 차트 Rounded
- [x] Dummy Data 날짜 수정
- [x] 색상 수정 
- [ ] y값 그래프 하단에 보이기
- [ ] x값 그래프 하단에 보이기
- [ ] 날짜 넣기
