### ISSUE TITLE
[feat] 히트맵 슬라이더 구현

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#217]
## 🐲 Description
히트맵 슬라이더를 구현합니다.

## 🧑‍💻 Todo
- [ ] 히트맵 슬라이더 구현.
- [ ] 점 개수 시간 상관없이 100개로 조정.
- [ ] 메인화면 내려서 새로고침 구현.

## ✏️ ETC
