### ISSUE TITLE
[feat] 버튼 쪼개지는 애니메이션 구현

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#22]
## 🐲 Description
<img width="563" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/0c0c540d-3e53-4d14-ade0-a70e7c2303fb">

<img width="120" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/8460e065-a1ff-4a1e-8d96-87057e2504df">

<img width="95" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/fe126d73-9525-459f-ac42-35a5f23e5a58">

피그마에서 이 부분을 작업해볼게요! 

## 🧑‍💻 Todo
- [ ] 애니메이션 로직 추가
- [ ] 사라지는 애니메이션 설정
- [ ] 진행중과 일시정지 스테이트를 나눠서 적용
- [ ] 일시정지를 누르면 현재 까지 진행중인 무채색 GameProgressView를 보여줌
- [ ] 재개를 누르면 다시 색이 돌아온 GameProgressView를 보여줌
- [ ] 재개를 누르거나 종료를 누르면 둘로 나눠져있던 원이 하나로 붙으면서 끝내기 문구를 보여줌
- [ ] 끝내기 문구 뷰 생성
- [ ] 재개와 종료, 일시 정지 사이에 화면 전환 로직

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
오늘도 화이팅입니다. 빨리 해볼게요 ~
