### ISSUE TITLE
[feat] Information Button 구현

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#222]
## 🐲 Description
Information Button 구현

## 🧑‍💻 Todo
- [ ] 이미지 에셋 "InformationIcon" 사용
- [ ] 접혀있을 땐 하얀색 스트로크 적용
- [ ] 펼쳐졌을 땐 회색 스트로크 적용
- [ ] 펼쳐지는 에니메이션 추가
