### ISSUE TITLE
[feat] 워치 관련 오류 수정

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#226]
## 🐲 Description
- 워치에서 수정할 사항들을 반영합니다

## 🧑‍💻 Todo
- [x] 게이지바 수정
- [x] 경기 시간 색상 변경
- [x] 명언 뜨는 시간 더 길게
- [ ] 심장 색상 민트색으로 에셋 변경
- [x] 게이지바 속도 초기화
- [x] 데이터 단위 확인

**Comment by Damagucci-Juice** [comment]
@yunwkgus 명언 뜨는 시간 제가 했는데 호호...

<img width="879" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/eb1143d6-6ff1-4246-931e-905619c7fc39">

관련 PR: #227
