### ISSUE TITLE
[fix] 기본적인 유아이 수정

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#231]
## 🐲 Description
작업 내용을 작성해 주세요.

## 🧑‍💻 Todo
- [x] 스크롤뷰 인디케이터 모든 뷰에서 안보이게 하기
- [x] 프로필 뷰 밑선 맞추기
- [x] 모든 경기 -> 디테일 경기 : 백 버튼 타이틀 생기는데 이 것 제거
- [x] 모든 경기 뷰에서 타이틀 부분 패딩 주기
- [x] 워치: 시간 깨지는 버그
- [x] 인포메이션버튼에서 안내 문구 수정(장난스러운 문구 수정, 별도의 뷰로 분리)
- [ ] 뱃지에서 별 두개 넣기 -> 일해라 웨슬리
- [x] 공유 기능 터지는 것 수정
- [x] 미디어 버튼 패딩 아래로 주기

<img width="735" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/6177e1e9-e0c4-47b2-bdca-81a759b8945e">

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

**Comment by Damagucci-Juice** [comment]
- 프로필뷰 밑선 맞추기
<img width="235" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/e5ea39cd-ee02-4fb1-bb1c-c428ed08a6c5">
