### ISSUE TITLE
[release] 추가 수정 및 Version 1.0.1 업로드

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#233]
## 🐲 Description
앱스토어 배포 전 버전 1.0.1 입니다.

## 🧑‍💻 Todo
- [ ] 오타 수정 InfomationButton -> InformationButton
- [ ] InformationButton View 추가
- [ ] 심박수 최대 최소 두 줄 넘어가는 것 수정
