### ISSUE TITLE
[fix] 추세, 프로필 사진, Infobutton 수정 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#238]
## 🧑‍💻 Todo
- [ ] 추세 그래프 같은 날에 여러 경기가 있을 시 시간 순서로 정렬
- [x] 프로필 사진 정렬 흐뜨러지는 것 수정
- [x] InfoButton 움직이는 듯한 버그 수정

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
