### ISSUE TITLE
[fix] 앱스토어에 리포트된 버그 수합 + 픽스 계획

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#266]
## 🐲 Description
앱스토어에서 제기된 버그 확인하고 버그 리포트하는 창구 알아보겠습니다. 

## 🧑‍💻 Todo
- [x] 앱스토어에서 리포트된 버그 목록화
- [x] 버그 이유 조사 
- [x] 버그 해결 초안
- [x] 버그 수합하는 창구 조사
- [x] 버그 수합하는 창구 구현
- [x] workout이 중복되어서 여러번 보여지는 버그 수정

## ✏️ ETC
시간과 능력이 된다면 해결과 구현까지 하도록 노력하겠습니다.
