### ISSUE TITLE
[fix] 쇼케이스 수정사항 적용

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#27]
## 🐲 Description
쇼케이스 수정사항을 적용.

## 🧑‍💻 Todo
- [x] 모달 백그라운드 수정.
- [x] 텍스트 행간, 상단 패딩값.
- [x] 그래프 UI, 플로우 수정.
- [x] 리스트 overlay 적용.

## ✏️ ETC
자고싶어요.
