### ISSUE TITLE
[feat] 권한 변경 이후 앱 새로고침

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#283]
## 🐲 Description
- 헬스킷 권한과 위치 권한 변경 이후 앱을 새로고침합니다.

## 🧑‍💻 Todo
- [ ] 헬스킷 권한 변경 확인
- [ ] 위치 권한 변경 확인
- [ ] 새로 시작할 때 화면

## ✏️ ETC
늦어서 미안합니다-!
