### ISSUE TITLE
[fix] TabBar 커스텀 수정

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#29]
## 🐲 Description
ContentView 탭 바 커스텀 수정

## 🧑‍💻 Todo
- [ ] 탭바 배경색 변경
- [ ] 탭바 아이콘 이미지로 대체
- [ ] 탭바 타이틀 수정
