### ISSUE TITLE
[fix] 작은 버그들 수정

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#303]
## 🐲 Description
버전 업데이트 전 버그 수정입니다. 

## 🧑‍💻 Todo
- [x] 워치에서 명언 심장 움직임 오류 수정 (30분 투자)
- [x] Match recap view player 이름 오류 없이 표현되게 수정
- [x] 설정 권한 앱 실행 위치
