### ISSUE TITLE
[fix] 서비스 개선을 위한 기능 추가

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#324]
## 🐲 Description
- 인터뷰 기반 ux 개선 과제입니다. 

## 🧑‍💻 Todo
- [x] 가속도 측정이 어떻게 되는지 데이터 정확성 → 파워로 대체(와트) 
- [x] 지도에서 데이터의 편차를 안내
- [x] 워치에서 심박을 좀 더 잘 알려주기 (ex, 엘리베이터 위아래 표시, 아래 쉐브론) 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
