### ISSUE TITLE
[fix] Navigation Title 위에 불필요한 공간 제거

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#331]
## 🐲 Description
작업 내용을 작성해 주세요.

## 🧑‍💻 Todo
- [x] Trendchart 위에 공간 제거
- [x] 경기 요약 리스트 위에 공간 제거
- [x] 디테일 한 경기 위에 공간 제거
- [x] 프로필 위에 공간 제거

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
