### ISSUE TITLE
[feat] Apple Watch 안내 온보딩뷰 구현

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#340]
## 🐲 Description
데이터가 없을 때 온보딩뷰가 자동으로 올라올 수 있게 구현합니다.

## 🧑‍💻 Todo
<img width="210" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/106143629/fd403111-84e4-4d06-b08b-63eef0d6e409">

- [ ] 데이터가 없을 때 온보딩뷰가 자동으로 올라오도록 설정
- [ ] 글, 워치 사진 추가
- [ ] 닫기 버튼 구현
