### ISSUE TITLE
[feat] EmptyView MainView 통합

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#341]
## 🐲 Description
EmptyView와 MainView를 통합합니다.

## 🧑‍💻 Todo
- [ ] EmptyView제거
- [ ] 데이터가 없을 시 빈 데이터의 MainView로 진입
- [ ] 데이터 받아오는 로직 변경
- [ ] 데이터가 없을 시 온보딩 뷰가 올라오도록 구현
