### ISSUE TITLE
[feat] Heatmap Slider + Watch Time Indicator + Watch Icon Unification

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#379]
## 🐲 Description
1.1.5 업데이트 세부 반영 사항입니다.

## 🧑‍💻 Todo
- [x] 히트맵 슬라이더 변경 : 기본 100% 맵 표시 (빨강색)+ 슬라이더로 그 당시 위치 표시
- [x]  Time Indicator 색상 변경 피그마
- [ ]  워치 앱 내 하트 통일 + 피그마

## ✏️ ETC
- 피그마 작업 참고 부탁드립니다.
