### ISSUE TITLE
[feat] 레이더 차트 색상 조절, 추세 조정

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#381]
## 🧑‍💻 Todo
- [ ] 추세에서 문구 랜덤하게 던지게 수정
- [ ] 추세에서 WorkoutData를 Main과 동기화
- [ ] MatchDetailView에서 빨간색은 평균경기로, 민트색은 이번경기로 표시

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
