### ISSUE TITLE
[feat] 워치 심박 연속 차트 

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#394]
## 🐲 Description
워치 심박 연속 차트 & 칼로리 수집을 개발합니다.

## 🧑‍💻 Todo
- [x] 워치 심박 연속 수집
- [x] 워치 심박 연속 차트 표현
- [x] 워치 칼로리 수집 데이터 확인
