### ISSUE TITLE
[feat] 워치 workoutsessionManager 구현

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#4]
## 🐲 Description
SoccerBeat 린트 세팅

## 🧑‍💻 Todo
- [x] 권한 설정
- [x] 기본 정보 받기
- [x] 최대 심박수 받기
- [x] zone 5 심박수 나눠 설정하기 
- [x] 스프린트 갯수 측정하기

## ✏️ ETC
5분 연속 zone 5 심박수 -> 쇼케이스에는 카톡 알림으로 구현하는 걸로 하겠습니다 -!
