### ISSUE TITLE
[feat] HealthAlert 모달 로컬라이제이션

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#411]
## 🐲 Description
HealthAlert 모달 로컬라이제이션

## 🧑‍💻 Todo
- [ ] HealthAlert 모달 이미지를 코드로 구현 후 로컬라이제이션 적용
- [ ] Tooltip 로컬라이제이션 적용
- [ ] 뱃지 문구 영어로 통일
- [ ] 
- [ ]
