### ISSUE TITLE
[feat] 차트 디테일 수정

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#413]
## 🐲 Description
차트 디테일 수정

## 🧑‍💻 Todo
- [ ] 데이터 순서 변경(최신 데이터가 오른쪽으로)
- [ ] 단위를 따로 우 상단으로 빼기
- [ ] 차트 간격 촘촘하게 바꾸기
- [ ] 날짜 월 추가
