### ISSUE TITLE
[fix] 워치 화면 전환 디테일 수정 

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#42]
## 🐲 Description
화면 전환 전반적으로 디테일 잡습니다.

## 🧑‍💻 Todo
- [x] Start 이후 화면 전환
- [x] Control 화면에서 버튼 이동
- [x] Control 화면에서 버튼 클릭시 자동 화면 전환
- [x] SummaryView 에서 완료 버튼 클릭시 Start Button 화면 보기
