### ISSUE TITLE
[feat] 영어 UI 수정

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#431]
## 🐲 Description
영어 UI 수정합니다.

## 🧑‍💻 Todo
- [ ] MainView "Recent Game" 줄바꿈 수정
- [ ] ProfileView Info Badge 두 줄 되는 현상 수정
- [ ] ShareView 이름이 제일 길 때 세 줄 되는 현상 수정
- [ ] 데이터 에러 뷰 문단 수정

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
