### ISSUE TITLE
[feat] 인앱리뷰 기능 추가

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#433]
## 🐲 Description
인앱리뷰 기능을 추가합니다.

## 🧑‍💻 Todo
- [ ] 사용자에게 App Store 평가 및 리뷰를 요청합니다.
- [ ] 인앱리뷰 요청 로직 확인
- [ ] 유저 인앱리뷰 사용 여부 데이터 수집
- [ ] 긍정 여부 확인 후 앱 리뷰 유도

## ✏️ ETC
https://developer.apple.com/documentation/storekit/requesting_app_store_reviews
https://green1229.tistory.com/420
https://www.youtube.com/watch?v=_oTPT3gFUms
https://www.youtube.com/watch?v=OpNj_VrOL-g

- 앱 사용 횟수에 따른 리뷰 요청
```
import StoreKit

class ReviewManager {
    
    static let minimumAppLaunches = 5
    static let minimumFeatureUsage = 3
    
    static func incrementAppLaunches() {
        let currentLaunches = UserDefaults.standard.integer(forKey: "appLaunches") + 1
        UserDefaults.standard.set(currentLaunches, forKey: "appLaunches")
        checkAndRequestReview()
    }
    
    static func incrementFeatureUsage() {
        let currentUsage = UserDefaults.standard.integer(forKey: "featureUsage") + 1
        UserDefaults.standard.set(currentUsage, forKey: "featureUsage")
        checkAndRequestReview()
    }
    
    static private func checkAndRequestReview() {
        let launches = UserDefaults.standard.integer(forKey: "appLaunches")
        let usage = UserDefaults.standard.integer(forKey: "featureUsage")
        
        if launches >= minimumAppLaunches || usage >= minimumFeatureUsage {
            requestReview()
        }
    }
    
    static private func requestReview() {
        if #available(iOS 10.3, *) {
            SKStoreReviewController.requestReview()
        }
    }
}
```

1. 사용자 행동 기반 로직
특정 목표 달성 후: 사용자가 앱 내에서 주요 목표를 달성했을 때 (예: 게임의 레벨을 클리어하거나, 앱 내 중요한 기능을 성공적으로 사용했을 때) 리뷰 요청을 띄웁니다. 이런 타이밍은 사용자가 긍정적인 감정을 느끼고 있을 가능성이 높기 때문에 효과적입니다.
N회 사용 후: 앱을 N회 실행한 후 또는 특정 기능을 N회 사용한 후에 리뷰 요청을 할 수 있습니다. 예를 들어, 사용자가 앱을 5번 사용했거나, 10개의 항목을 업로드했을 때 등입니다.
특정 시간 경과 후: 앱을 처음 설치한 후 일정 기간(예: 1주일 또는 1개월)이 지난 후 리뷰를 요청할 수 있습니다. 이는 사용자가 앱에 대해 충분히 경험한 후 리뷰를 남길 수 있도록 유도합니다.

2. 이벤트 기반 로직
업데이트 이후: 새로운 기능이나 버전 업데이트 후 사용자가 해당 기능을 사용한 후 리뷰 요청을 띄우는 방법도 있습니다. 사용자가 새로운 업데이트에 만족했을 때 긍정적인 리뷰를 남길 가능성이 높습니다.
고객 서비스 완료 후: 고객 서비스와 관련된 요청이 성공적으로 해결된 후, 이를 통해 사용자의 만족도를 높인 뒤 리뷰를 요청할 수 있습니다.

3. 리뷰 요청의 제한
적절한 간격 유지: 애플은 앱에서 너무 자주 리뷰 요청을 띄우지 않도록 권장합니다. 시스템은 자동으로 일정 주기 내에 너무 많이 요청되는 것을 방지하지만, 개발자가 내부적으로 별도의 제한을 설정할 수 있습니다.
예를 들어, 마지막으로 리뷰를 요청한 후 최소 3~6개월 동안 추가 리뷰 요청을 하지 않도록 하는 로직을 설정할 수 있습니다.
사용자 선호도 반영: 이전에 리뷰를 남긴 사용자에게 다시 리뷰 요청을 띄우지 않도록 설정하는 것도 좋은 방법입니다. 예를 들어, 리뷰 요청 후 사용자가 실제로 리뷰를 남겼는지 확인한 후 다시 요청하지 않도록 관리합니다.

### 고려사항
- ex) 앱을 10회 이상 사용한 유저 -> 10회 이상 사용했다는 것은 앱에 대한 기대가 높고 사용 의지가 있다는 뜻
- 리뷰 요청 제한 -> 한 번 리뷰를 남긴 사람에겐 다시 요청이 가지 않도록 로직 확인
- 앱 사용 긍정 여부 확인 후 평가를 유도하는 방식 -> 긍정 평가를 유도할 수 있음
