### ISSUE TITLE
[fix] Stationary `Close` 버튼 누르면 뒤의 시간에 영향이 가는 버그

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#467]
## 🐲 Description
Stationary `Close` 버튼 누르면 뒤의 시간에 영향이 가는 버그

## 🧑‍💻 Todo
- [x] Pause/Stop를 누른 상황에서도 Stationary 뷰가 활성화 되는 것을 막기
- [x] Resume을 누르면 재게
- [ ] 행동 위치 권한이 읽히는 시점을 조정

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
![image](https://github.com/user-attachments/assets/ef129b24-c95a-45c6-9ca2-6f5b53e18155)

- DetactStationaryView에서 `close` 버튼을 눌렀을 때 뒤에 표시되던 경기 시간이 영향이 간다는 제보가 있어서 재현해보려 했는데 재현이 안됨
- 행동 권한 요청을 읽히는 시점을 조정하려 했는데, 최초 앱 설치시 한번이라 그렇게 영향이 없을 것 같음
- - 위치 획득 권한과 다르게 CoreMotion에서 모션 획득 권한 요청이 별도의 API가 없음, 그냥 core motion start와 권한 요청이 같이 감

**Comment by hyungminkimdev** [comment]
# Close 버튼 누르면 시간이 멈추고, 다시 운동을 시작하면 원래 상태로 돌아오는 제보 영상입니다!

@Damagucci-Juice 


https://github.com/user-attachments/assets/654e94cf-e883-4ed4-9405-be30067b2497
