### ISSUE TITLE
[fix] QA 중 에러 수정

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#471]
## 🐲 Description
에러를 수정합니다.

## 🧑‍💻 Todo
- [x]  배경음악 재생 확인
- [x]  카드 플립 소리 재생 확인
- [x]  Running 진행중인 것 아이폰에 뜨게
- [x]  명언이 간헐적으로 두 번 뜨는 현상
