### ISSUE TITLE
[feat] 히트맵 수정

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#474]
## 🐲 Description
히트맵 수정합니다.

## 🧑‍💻 Todo
- [ ] 디자인 색상 변경
- [ ] 루트 데이터 개수에 따라 비율로 히트맵 강도 나누기
- [ ] 대서양 데이터 찍히는지 확인
