### ISSUE TITLE
[feat] 위도, 경도를 입력받아 히트맵 구현.

### ISSUE THREAD

**Issue by imhotdogboy** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#50]
## 🐲 Description
위도, 경도를 입력받아 히트맵 구현.

## 🧑‍💻 Todo
- [x] google map의 히트맵을 구현합니다.
- [ ] LFHeatMap의 히트맵을 구현합니다.
- [ ] JDSwiftHeatMap의 히트맵을 구현합니다.
- [x] 직접 히트맵을 구현합니다..

## ✏️ ETC
- https://www.reddit.com/r/SwiftUI/comments/102vtqe/google_maps_sdk_heatmap_wont_update_upon_array/
- https://github.com/gpolak/LFHeatMap
- https://github.com/jamesdouble/JDSwiftHeatMap
- https://developer.apple.com/forums/thread/717386
