### ISSUE TITLE
[feat] 속도계, 스프린트 적용

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#52]
## 🐲 Description
애플워치 메인에 속도계와 스프린트를 구현합니다.  
- 현재 속도 기반으로 속도계 게이지 구현.
- 속도가 스프린트 기준을 초과했을 경우

## 🧑‍💻 Todo
- [ ] 애플워치 메인 화면에 속도계를 구현합니다.
  - [ ] 스프린트 게이지에 화려한 효과가 나타남
  - [ ] 우측 카운터의 스프린트 횟수가 증가함
  - [ ] 속도가 스프린트 기준 이하로 떨어질 경우 돌아옵니다.
- [ ] 속도계 우측에 스프린트 횟수를 구현합니다.

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
