### ISSUE TITLE
[feat] 축구 명언 추가

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#54]
## 🐲 Description
축구 명언을 조사해서 프로젝트 파일에 넣습니다. 

## 🧑‍💻 Todo
- [ ] 축구 명언 조사
- [ ] JSON 타입으로 선언 
- [ ] 세션 완료시에 뷰에 띄우기 
- [ ] 필요하다면 폰트 조정
    - [ ] 이미지를 제거한 버전의 경기 완료 뷰 보여주기
- [ ] 한국어 버전과 영어 버전 둘로 나눠서 보여주기

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
