### ISSUE TITLE
[feat] iOS 수정된 뷰 구현

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#58]
## 🐲 Description
iOS 성피, 조엘, 길벗 피드백 후 수정된 디자인 뷰 구현

## 🧑‍💻 Todo
- [ ] 스크롤 뷰(+LazyVStack) 구현
- [ ] 모든 기록 보기 + 버튼 구현
- [ ] 각 경기 데이터 버튼 구현
- [ ] 맨 위로 올라가기 버튼 구현
