### ISSUE TITLE
[fix] 작업 변경 사항 오류

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#70]
## 🐲 Description
작업 내용을 작성해 주세요.

https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/b3e94f70-e808-4fcd-982e-fdb40b1d4eed

https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/676d223f-bbd2-4010-ae2b-7ff39fd7bf40

https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/ad06a0f2-6cbf-45c5-a735-6a405ef26b0c

![Simulator Screenshot - Apple Watch SE (40mm) (2nd generation) - 2023-11-01 at 02 14 03](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/b42e8225-3d88-4e90-9770-091388ad20b3)
![Simulator Screenshot - Apple Watch SE (40mm) (2nd generation) - 2023-11-01 at 02 14 12](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/c87b523d-cefb-48fa-9c86-5d4b03dbee8e)
![Simulator Screenshot - Apple Watch SE (40mm) (2nd generation) - 2023-11-01 at 02 14 23](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/d705abe1-5ab4-4183-85e3-83049063f6fb)
<img width="802" alt="Screenshot 2023-11-01 at 2 14 51 AM" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/3baa4936-9c26-4f11-90d8-483bc8a70899">

## 🧑‍💻 Todo
- [x] 심장맥박 변화에 따른 Zone 변화 사라짐
- [x] 일시 정지하면 화면 다 가리는데 정보를 못봄
- [x] 실기기는 등록이 안되어있어서 못하는데 시뮬레이터에선 워크아웃이 생성되지 않아서 강제 언래핑했을 때 시뮬레이터 꺼지는 오류 발생
- [x] 명언뷰에서 너무 큰게 보일 때 화면을 넘어가는 버그
- [x] 춤추는 BPM

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

**Comment by yunwkgus** [comment]
고생 많으셨습니다 ! 멋지네요 
춤추는 bpm 아 저걸
