### ISSUE TITLE
[fix] 워치 수정 사항 반영합니다. 

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#72]
## 🐲 Description
작업 내용을 작성해 주세요.

## 🧑‍💻 Todo
- [x] 쉴 때 정보 일시 중지 화면
- [x] 일시 정지 - 중지 색상 변경
- [x] 워크아웃 강제 언래핑 해결

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
