### ISSUE TITLE
[feat] MatchDetailView 구현

### ISSUE THREAD

**Issue by hyungminkimdev** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#75]
## 🐲 Description
MatchDetailView 구현

## 🧑‍💻 Todo
- [ ] 모달뷰 -> 스크롤 뷰로 변경 구현
- [ ] 장점, 활동 히트맵 문구 추가
- [ ] 히트맵, BPM 이미지 추가
- [ ] Sprint 타임 블럭 구현
