### ISSUE TITLE
[feat] 맥박과 거리데이터를 읽기 전에 0 대신 "--'--" 으로 표현

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#78]
## 🐲 Description
- UX를 높이기 위해 workout이 동작하거나 아직 업데이트가 안되었을 때의 기본형을 표시를 하려고 합니다. 
- 추가적으로 경기 시간에서 밀리초가 안나오게 작업하려고 합니다. 

## 🧑‍💻 Todo
- [x] BPM 기본형 "---"으로 변경
- [x] 뛴 거리 기본형 "--"으로 변경, 단위 정보도 사라지게 하기
- [x] 경기 시간에서 밀리초 제거

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

최근에도 밀리초가 찍혔나요? 코드상으로는 밀리초는 담기지 않게 되어있긴 하네요.

- `ElapsedTimeView.swift` Line 22
<img width="489" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/f06f9141-9f7c-4e80-a589-36140fce38a5">
