### ISSUE TITLE
[feat] Workout Manager Mockup version 만들기 

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#80]
## 🐲 Description
- WorkoutManager를 사용하는 코드에서는 Preview가 동작하지 않는 에러가 발생해서 이를 해결할 수 있도록 작업을 해봐도 좋겠습니다!
- 당장의 우선순위는 낮습니다.

## 🧑‍💻 Todo
- [ ] WorkoutManager를 감당할 수 있는 Protocol 생성
- [ ] TestWorkoutManager를 만들어서 Debug 환경에서는 이를 확인하도록 수정
- [ ] Preview 사용가능한지 테스트 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
