### ISSUE TITLE
[fix] 1101 워치 최종 버전 수정

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#83]
## 🐲 Description
- 워치에서 걸리는 것들 최종적으로 수정할게요.

## 🧑‍💻 Todo

**호제**
- [ ] 일시 정지하면 BPM 회색 그라데이션
- [ ] 존 셀 height 변경 14 -> 16

**구찌**
- [x] Bpm 글자 애니 빼기 + BPMTextView Group에서 빼기 
- [x] Zone graph 화면 꽉 채우기
- [x] Pull Request 템플릿 설정하기
- [x] 명언 뷰 화면 넘어가지 않게 하기 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
