### ISSUE TITLE
[feat] iOS-모든 기록 보기 뷰 + WatchOS 명언뷰 하트 위치 고정

### ISSUE THREAD

**Issue by Damagucci-Juice** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#89]
## 🐲 Description
<img width="272" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/c4c94c2f-b9c0-4c83-b6e1-f7cabe2859a4">
<img width="371" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo/assets/50472122/3509087c-800b-43cf-8edb-ecdf2dd65094">

## 🧑‍💻 Todo
- [ ] 명언뷰 하트 위치 고정
- [ ] 모든 기록 보기 뷰 만들기
- [ ] 그안에 작은 컴포넌트 만들기 
- [ ] 프로그래밍적으로 ForEach 돌리기

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.

화이팅~~
