### ISSUE TITLE
[feat] watch CLLocationManager 수정

### ISSUE THREAD

**Issue by yunwkgus** [DeveloperAcademy-POSTECH/MacC-Team10-Guryongpo#90]
## 🐲 Description
어떻게 하면 워치에서 루트 정보를 받아오는가

## 🧑‍💻 Todo
- [x] info plist 권한 추가
- [x] corelocation 인스턴스 생성
- [x] 사용자 디바이스 위치 서비스 활성화 확인
- [x] 앱 위치 권한 부여 상태 확인 매서드
- [x] delegate 설정 & protocol 채택 

## ✏️ ETC
메모 및 전달 사항을 작성해 주세요.
